### ISSUE TITLE
使用docker 无法启动，使用debug 模式也无法启动

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [Innei/nest-http-prisma-zod#36]
### Describe the bug

WARN[0000] The "ALLOWED_ORIGINS" variable is not set. Defaulting to a blank string.
WARN[0000] The "JWT_SECRET" variable is not set. Defaulting to a blank string.

感觉docker 配置有些问题。

执行：docker-compose up。也报错

### Reproduction

docker build . -t innei/nest-http-prisma-zod

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 182.40 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/Library/pnpm/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/Library/pnpm/npm
    pnpm: 8.3.1 - ~/Library/pnpm/pnpm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 114.0.5735.106
    Edge: 114.0.1823.43
    Safari: 16.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
具体是什么报错？

**Comment by Darkhorse-Fraternity** [comment]
1. pnpm run prisma:generate && pnpm run migrate:dev   无法找到正确的env 文件
<img width="555" alt="image" src="https://github.com/Innei/nest-http-prisma-zod/assets/5756752/ccd251ff-47f6-4b3f-80f5-89b7099c63bc">

2. 
<img width="1102" alt="image" src="https://github.com/Innei/nest-http-prisma-zod/assets/5756752/89524a9e-fe83-4da3-91c0-50a1b59b673b">
这边是否需要调整，才能使用我本地的修改？x

3.gitignore 如果没有加上apps/core/node_modules， 会出现node_modules被错误加进来。项目是否可以采用turbpRepo 来进行管理，将prisma,external 放到packages 里面做管理？

**Comment by Innei** [comment]
1. `cp .env.template .env`
2. 没懂，这本身就是模板项目。你要改自己改呗
3. 不考虑用 turbo
