### ISSUE TITLE
pnpm run init 出现bug

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [Innei/nest-http-prisma-zod#43]
### Describe the bug

执行pnpm run init 报错：
> @nest-http/private@ migrate:dev /Users/tonyyo/Documents/Project/pumpkii/pumpkii-nest
> pnpm -C prisma run migrate:dev

> @nest-http/prisma@ migrate:dev /Users/tonyyo/Documents/Project/pumpkii/pumpkii-nest/prisma
> prisma migrate dev

Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:37
   |
36 |   provider = "postgresql"
37 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 5.3.1
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 
 ---
子目录prisma 无法读取到根目录.env 文件，只有将根目录.env 复制一份到prisma 文件夹下才可以。

### Reproduction

pnpm run init

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.39 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.7.6 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 114.0.5735.106
    Edge: 114.0.1823.43
    Safari: 16.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
看上去软连接失效了

**Comment by Innei** [comment]
把 软连接 加上了。感谢反馈
