### ISSUE TITLE
能否帮忙添加一个launch.json

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [Innei/nest-http-prisma-zod#44]
### Clear and concise description of the problem

无法通过vscode 来debug

### Suggested solution

这个是我自己添加的
···
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Debug Nest Framework",
        "runtimeExecutable": "npm",
        "runtimeArgs": [
          "run",
          "dev",
          "--",
          "--inspect-brk"
        ],
        "autoAttachChildProcesses": true,
        "restart": true,
        "sourceMaps": true,
        "stopOnEntry": false,
        "console": "integratedTerminal",
      }
    ]
}
···
但是发现不奏效，进不了断点。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
哥，可以用 JavaScript Debug Terminal
![CleanShot 2023-11-24 at 3  27 05@2x](https://github.com/Innei/nest-http-prisma-zod/assets/41265413/eb886717-a906-4aac-9cc3-f81843c580fc)

要什么 launch.json
