### ISSUE TITLE
api-docs  打开后是404

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [Innei/nest-http-prisma-zod#45]
### Describe the bug

就按着文档启动的。api-docs 打开后报404

### Reproduction

pnpm dev

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 383.57 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.7.6 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 114.0.5735.106
    Edge: 114.0.1823.43
    Safari: 16.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Darkhorse-Fraternity** [comment]
我这边加了
import { patchNestJsSwagger } from 'nestjs-zod'
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger'


patchNestJsSwagger()
const createDocument = (app: INestApplication) => {
  const config = new DocumentBuilder()
    .setTitle('Pumpkii-api')
    .setVersion('1.0')
    .build()
  const document = SwaggerModule.createDocument(app, config)
  SwaggerModule.setup('api-docs', app, document)
}

但是发现dto 只有@body 的时候才被文档识别。

**Comment by Innei** [comment]
我不喜欢 swagger
